### PR TITLE
Bulk grammar update

### LINKED ISSUE #20: Preprocessor as function parameter is parsed as error
Parser Error examples:
NUM-ENTRIES (target-external, {&DELIM}).
ENTRY(i, target-external, {&DELIM}). 

Image

### LINKED ISSUE #22: Macro variable assignment inside preprocessor returns a parser error
When trying to assign a macro variables value inside a preprocessor it returns a parser error:
run aqua.p ({&action=query}).

### LINKED ISSUE #23: Preprocessor inside include results in a parser error
In the example we have an include statement, that takes the path to the include file from a macro variable, which results in a parse error. When the macro variable is removed and replaced with a static path name it works fine. The parser doesn't recognize another preprocessor in the include statement.

Image

### LINKED ISSUE #24: Preprocessor GET and SET calls with handle arguments result in parse error
When calling the getter or setter through the preprocessor with handle arguments, the parser fails to parse the GET or SET keyword in the brackets and analogically throws a parse error for the handle arguments because it doesn't expect them.

Examples:
`{get ObjectType cObjectType phInstance}.`
`{set ObjectType cObjectType phInstance}.`

Image

### LINKED ISSUE #25: Preprocessor directives are not taken as part of an ASSIGN block
If we have an `ASSIGN` statement in which there is a preprocessor directive it is not recognized as part of it and it is formatted incorrectly, for example:
```
ASSIGN 
    var1 = var2
  &IF {&DELIM} <> ",":U &THEN
    tbllist = REPLACE (tbllist, {&DELIM}, ",":U)   
  &ENDIF
      change = yes.
```
After Formatting:
```
ASSIGN
  var1 = var2
  .
  &IF {&DELIM} <> ",":U &THEN
    tbllist = REPLACE (tbllist, {&DELIM}, ",":U)   
  &ENDIF
      change = yes.
```
In the after it doesn't recognize that `&IF ... &ENDIF` is part of the `ASSIGN` block and puts a dot at the last assignment before the preprocessor directive, if there are more than one assignments after the directives, formatter will cause a syntax error.
Expected Code:
```
ASSIGN
  var1 = var2
  &IF {&DELIM} <> ",":U &THEN
    tbllist = REPLACE (tbllist, {&DELIM}, ",":U)   
  &ENDIF
  change = yes.
```

### LINKED ISSUE #27: Widget references in function names causes parsing issue
When there's a widget reference in function name the preprocessor directive takes up the remaining code in the line.
Examples:
`qbf-a = qbf-t&:LOOKUP(qbf-t:SCREEN-VALUE) IN FRAME qbf-both.`
`qbf-a = qbf-t:LOOKUP(qbf-t&:SCREEN-VALUE) IN FRAME qbf-both.`

Image

### LINKED ISSUE #28: Variable definition with '&' in name is parsed as error
When trying to define a variable and add the `&` symbol to the name, it shows an error on the symbol and it can't be parsed, for example:
`DEFINE VARIABLE fTitle& AS CHARACTER NO-UNDO.`

Image

### LINKED ISSUE #29: Preprocessor inside frame definition parses as error
`DEFINE FRAME {&FRAME_NAME} bPolicy AT COLUMN 2 ROW 2.`
In this code, the preprocessor is parsed as an error, when replaced with a string it parses fine, aprt from the fact taht frame definition is not yet working in the parser.

Image

### LINKED ISSUE #30: Complex preprocessor expression causes parser error
Parser doesn't recognize structure bellow which cause error.
`{&_proparse_ prolint-nowarn(overflow)}`

Image

### LINKED ISSUE #31: Method call in WHEN clause of CASE statement causes parser failure
Method call inside CASE declaration and WHERE clause causes parsing failure:
'case pData:type:
     when DataTypeHelper:GetMask(DataTypeEnum:XmlDocument) then
         do:
             pData:save(DataTypeEnum:Memptr:ToString(), mXml).
         end.
end case.'

Image

### LINKED ISSUE #32: Indentifiers with DATASET keyword prefix parsed as error
When indentifier name starts with "dataset" it is parsed as dataset expression. Example:
'if valid-handle(DatasetHandle) then
  return DatasetHandle:get-top-buffer (1):name.'

Image

### LINKED ISSUE #33: Object access expression with IN FRAME causes parser error
When using structure below parser doen't recognize object access identifier with trailing IN FRAME keyword.
`btn_Save_Sel:SENSITIVE IN FRAME FRAME-A = FALSE .`

Image

### LINKED ISSUE #34: Assignment with object access with trailing IN FRAME keyword parser error
Trailing IN FRAME keyword after object access in assignment operation causes parser error.
`qbf-a = qbf-t:LOOKUP(qbf-t:SCREEN-VALUE) IN FRAME qbf-both.`

Image

### LINKED ISSUE #35: Top-level method with a name containing keyword causes parsing failure
If a method is in top level (i.e. inside include file) and contains keyword in the name, then it causes parsing error.

`method public static void NotType (input pArgument as Object, input poType as Progress.Lang.Class):`
    `define variable oDerivedClass as Progress.Lang.Class no-undo.`
`end method.`

Image

### LINKED ISSUE #36: Browse definition parses as error
DEFINE BROWSE bPolicy QUERY qPolicy
    DISPLAY ttPolicy.tcPolName COLUMN-LABEL "Policy Name"
            ttPolicy.tcPolDesc COLUMN-LABEL "Policy Description"
    WITH 6 DOWN WIDTH 65 MULTIPLE.

Image

### LINKED ISSUE #37: Rectangle definition parses as error
When defining a rectangle it causes an error due to the rectangle not being defined in the tree-sitter:
`DEFINE RECTANGLE rect_btns SIZE 1 BY 2.`
This causes a parser error.

Image

### LINKED ISSUE #38: VIEW-AS statement as RADIO-SET is parses as error
From: aderes_j-field2.p
When we are trying to define a variable and we add `VIEW-AS` statement, it is parsed as an error, for example:
```
DEFINE VARIABLE qbf-acdc AS CHARACTER NO-UNDO 
  VIEW-AS RADIO-SET HORIZONTAL RADIO-BUTTONS "A&scending", "A":u, 
  "Des&cending", "D":u SIZE 30 BY 1.
```

Image

### LINKED ISSUE #39: VIEW-AS statement as COMBO-BOX is parses as error
COMBO-BOX choice of VIEW-AS statement is not recognized by parser
```
DEFINE VARIABLE hist-date  AS DATE NO-UNDO FORMAT "99/99/9999"
  VIEW-AS COMBO-BOX LIST-ITEMS 07/04/1776, 07/11/1969, 09/10/1993.
```

Image

### LINKED ISSUE #40: Initializing variable with date without quotes parses as error
When defining a date variable and setting an initial value it is parsed as an error if it is not in quotes, for example:

`DEFINE VARIABLE hist-date AS DATE NO-UNDO FORMAT "99/99/9999" INITIAL 07/04/1776`

But this works fine:

`DEFINE VARIABLE hist-date AS DATE NO-UNDO FORMAT "99/99/9999" INITIAL "07/04/1776"`

Image

### LINKED ISSUE #42: DEFINE FRAME not being parsed
```
define FRAME SplashFrame
  SplashImage
  WITH SIZE-PIXELS 432 BY 266 NO-BOX FONT 4 BGCOLOR 8.
```

Image

### PR DESCRIPTION
**Pull request by SimasJakubenas**
Fixes #20 
Fixes #22 
Fixes #23 
Fixes #24
Fixes #25 
Fixes #27 
Fixes #28 
Fixes #29 
Fixes #30 
Fixes #31 
Fixes #32 
Fixes #33 
Fixes #34 
Fixes #35 
Fixes #36 
Fixes #37 
Fixes #38 
Fixes #39 
Fixes #40 
Fixes #42

### CODE REVIEW

File: grammar.js [hunk 1]
```diff
@@ -1315,13 +1359,13 @@ module.exports = grammar({
...
-    //       kw("LIST-ITEMS"),
-    //       kw("LIST-ITEM-PAIRS")),
-    //     _list($.string_literal,",")
-    //   ),
+    _list_items: ($) =>
+      seq(
+        choice(
+          kw("LIST-ITEMS"),
+          kw("LIST-ITEM-PAIRS")),
+        _list(choice($.string_literal, $.date_literal, $.number_literal, $._expression), ",")
```
Comment (eglekaz) [inline grammar.js]: Replace all three literals with `$._literal`

File: grammar.js [hunk 2]
```diff
@@ -1447,13 +1506,6 @@ module.exports = grammar({
     //     $._terminator
     //   ),
 
-    // _image_definition_option: ($) =>
```
Comment (eglekaz) [inline grammar.js]: If I remember correctly this should not be removed, because Image definition is still commented and this will be a part of it. Rather leave it commented here.

File: grammar.js [hunk 3]
```diff
@@ -278,25 +291,47 @@ module.exports = grammar({
...
 
     constant: ($) =>
       seq("{", optional("&"), $._constant_value, "}"),
 
-    _constant_value: ($) => choice($.identifier, $._integer_literal),
+    _constant_value: ($) => choice(
+      $.identifier, 
+      $._integer_literal,
+      seq($.identifier, "=", choice($.identifier, $._integer_literal, $.string_literal)),
+      seq($.identifier, repeat1(choice(/[\s\-()a-zA-Z0-9]+/)))
```
[the remark this answers is not in the document]
Comment (SimasJakubenas) [reply grammar.js]: added test case
